[project]
name            = "root_stubs"
version         = "0.1.0"
description     = "Example project using ROOT.RDF stubs with Pyright"
dependencies    = []

[project.optional-dependencies]
dev = [
    "pyright>=1.1.312",
]

