repos:
  - repo: local
    hooks:
      - id      : replace-sha
        name    : Latest -> SHA 
        entry   : hooks/replace_with_sha.sh
        language: script
        stages  : [pre-commit]
        types   : [yaml]
