# This file contains PT, ETA binning for PID maps for pions and Kaons and is
# meant to be used with PIDCalib2 through rx_pid. It is closer to what was used in Run1/2
# --------------------------------
bin: &bin_com
  log10(PARTICLE_PT):
  - 2.000
  - 2.700
  - 2.900
  - 3.000
  - 3.100
  - 3.200
  - 3.300
  - 3.400
  - 3.500
  - 3.600
  - 3.700
  - 3.800
  - 3.900
  - 4.000
  - 4.100
  - 4.200
  - 4.300
  - 4.400
  - 4.600
  - 5.000
  PARTICLE_ETA:
  - 2.0
  - 2.5
  - 2.9
  - 3.3
  - 3.7
  - 4.0
  - 4.5
  - 5.5
# --------------------------------
block_common: &b_com
  PARTICLE : *bin_com
# --------------------------------
b1: *b_com
b2: *b_com
b3: *b_com
b4: *b_com
b5: *b_com
b6: *b_com
b7: *b_com
b8: *b_com
