# This file is used to measure PIDe efficiencies for pions, kaons and electrons
# falling inside signal region, and above  0.2 in PROBNN_E
#
# -----------------------------------------------
samples  :
  b1  : 2024_WithUT_block1_v1
  b2  : 2024_WithUT_block2
  b3  : 2024_WithUT_block3
  b5  : 2024_WithUT_block5
  b6  : 2024_WithUT_block6
  b7  : 2024_WithUT_block7
  b8  : 2024_WithUT_block8
selection :
  - PARTICLE_PT              > 250
  - PARTICLE_P               > 3000
  - PARTICLE_TRACK_GHOSTPROB < 0.3
  - PARTICLE_IPCHI2          > 9
  - PARTICLE_PPHASRICH
  - PARTICLE_INECAL
# -----------------------------------------------
particles:
  Pi  :
    pid_cuts:
      - PROBNN_E > 0.2
      - DLLe     > 2.0
      - PROBNN_K < 0.1
    bin_vars :
      - log10(pi_PT)
      - ETA
  K   :
    pid_cuts:
      - PROBNN_E > 0.2
      - DLLe     > 2.0
      - PROBNN_K > 0.1
    bin_vars :
      - log10(K_PT)
      - ETA
