ntoys : 0
# ----------------
qsq_bin:
  - low
  - central
  - high
mva_cmb:
  - '030'
  - '040'
  - '050'
  - '060'
  - '070'
  - '080'
  - '085'
  - '090'
  - '092'
  - '094'
  - '095'
mva_prc:
  - '000'
  - '010'
  - '020'
  - '030'
  - '040'
  - '050'
  - '060'
  - '070'
  - '080'
  - '085'
  - '090'
