[project]
name            = "vector-stubs"
version         = "0.0.1"
description     = "Type stubs for the scikit-hep/vector package"
readme          = "README.md"
license         = {text = "MIT"}
dependencies    = []

