args:
  - {vers : v3, year : '2024', block : '1', proj : rkst_mm, brem : 0} 
  - {vers : v3, year : '2024', block : '2', proj : rkst_mm, brem : 0} 
  - {vers : v3, year : '2024', block : '3', proj : rkst_mm, brem : 0} 
  - {vers : v3, year : '2024', block : '4', proj : rkst_mm, brem : 0} 
  - {vers : v3, year : '2024', block : '5', proj : rkst_mm, brem : 0} 
  - {vers : v3, year : '2024', block : '6', proj : rkst_mm, brem : 0} 
  # ----------
  - {vers : v3, year : '2024', block : '1', proj : rkst_ee, brem : 0} 
  - {vers : v3, year : '2024', block : '1', proj : rkst_ee, brem : 1} 
  - {vers : v3, year : '2024', block : '1', proj : rkst_ee, brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '2', proj : rkst_ee, brem : 0} 
  - {vers : v3, year : '2024', block : '2', proj : rkst_ee, brem : 1} 
  - {vers : v3, year : '2024', block : '2', proj : rkst_ee, brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '3', proj : rkst_ee, brem : 0} 
  - {vers : v3, year : '2024', block : '3', proj : rkst_ee, brem : 1} 
  - {vers : v3, year : '2024', block : '3', proj : rkst_ee, brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '4', proj : rkst_ee, brem : 0} 
  - {vers : v3, year : '2024', block : '4', proj : rkst_ee, brem : 1} 
  - {vers : v3, year : '2024', block : '4', proj : rkst_ee, brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '5', proj : rkst_ee, brem : 0} 
  - {vers : v3, year : '2024', block : '5', proj : rkst_ee, brem : 1} 
  - {vers : v3, year : '2024', block : '5', proj : rkst_ee, brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '6', proj : rkst_ee, brem : 0} 
  - {vers : v3, year : '2024', block : '6', proj : rkst_ee, brem : 1} 
  - {vers : v3, year : '2024', block : '6', proj : rkst_ee, brem : 2} 
  # ----------
  # ----------
  - {vers : v3, year : '2024', block : '1', proj : rk_mm  , brem : 0} 
  - {vers : v3, year : '2024', block : '2', proj : rk_mm  , brem : 0} 
  - {vers : v3, year : '2024', block : '3', proj : rk_mm  , brem : 0} 
  - {vers : v3, year : '2024', block : '4', proj : rk_mm  , brem : 0} 
  - {vers : v3, year : '2024', block : '5', proj : rk_mm  , brem : 0} 
  - {vers : v3, year : '2024', block : '6', proj : rk_mm  , brem : 0} 
  - {vers : v3, year : '2024', block : '7', proj : rk_mm  , brem : 0} 
  - {vers : v3, year : '2024', block : '8', proj : rk_mm  , brem : 0} 
  # ----------
  - {vers : v3, year : '2024', block : '1', proj : rk_ee  , brem : 0} 
  - {vers : v3, year : '2024', block : '1', proj : rk_ee  , brem : 1} 
  - {vers : v3, year : '2024', block : '1', proj : rk_ee  , brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '2', proj : rk_ee  , brem : 0} 
  - {vers : v3, year : '2024', block : '2', proj : rk_ee  , brem : 1} 
  - {vers : v3, year : '2024', block : '2', proj : rk_ee  , brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '3', proj : rk_ee  , brem : 0} 
  - {vers : v3, year : '2024', block : '3', proj : rk_ee  , brem : 1} 
  - {vers : v3, year : '2024', block : '3', proj : rk_ee  , brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '4', proj : rk_ee  , brem : 0} 
  - {vers : v3, year : '2024', block : '4', proj : rk_ee  , brem : 1} 
  - {vers : v3, year : '2024', block : '4', proj : rk_ee  , brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '5', proj : rk_ee  , brem : 0} 
  - {vers : v3, year : '2024', block : '5', proj : rk_ee  , brem : 1} 
  - {vers : v3, year : '2024', block : '5', proj : rk_ee  , brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '6', proj : rk_ee  , brem : 0} 
  - {vers : v3, year : '2024', block : '6', proj : rk_ee  , brem : 1} 
  - {vers : v3, year : '2024', block : '6', proj : rk_ee  , brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '7', proj : rk_ee  , brem : 0} 
  - {vers : v3, year : '2024', block : '7', proj : rk_ee  , brem : 1} 
  - {vers : v3, year : '2024', block : '7', proj : rk_ee  , brem : 2} 
  # ----------
  - {vers : v3, year : '2024', block : '8', proj : rk_ee  , brem : 0} 
  - {vers : v3, year : '2024', block : '8', proj : rk_ee  , brem : 1} 
  - {vers : v3, year : '2024', block : '8', proj : rk_ee  , brem : 2} 
outputs:
  - fit_linear.png
  - fit_log.png
  - fit.pkl
  - no_pars_linear.png
  - no_pars_log.png
  - parameters.json
  - parameters.yaml
  - pars_linear.png
  - pars_log.png
  - post_fit.tex
  - post_fit.txt
  - cutflow.md
  - selection.yaml
