input:
  year:    # Supported years
    - 2024
  trigger:
    - Hlt2RD_BuToKpEE_MVA
  brem:   # Supported brem categories
    - 0
    - 1
    - 2
  cali:
    - 000
  samples: # Supported samples
    simulation : Bu_JpsiK_ee_eq_DPC
    data       : DATA*
  selection:
    #block : block == 1 || block == 2
    #hop   : (1)
    mass  : (1)
    q2    : Jpsi_Mass > 2200 && Jpsi_Mass < 3800
syst:
    - nom
fitting:
  ranges : # Fitting ranges for each brem category
    0 :
      - 2200
      - 3800
    1 :
      - 2200
      - 3800
    2 :
      - 2200
      - 3800
  mass    : Jpsi_M_brem_track_2 # Observable to be fitted
  binning :
    nbins : 60
  model:
    pdfs:
      - dscb 
    parameters: # Initial values of parameters used in fit
      mu   : 3060
      sg   : 20.0
      ap_r :  1.0
      pw_r :  1.0
      ap_l : -1.0
      pw_l :  1.0
      ncbr :  1000
      ncbl :  1000
  simulation:
    strategy  :
      retry   :
        ntries        : 4
        pvalue_thresh : 0.05
        ignore_status : true
