input:
  samples: # Supported samples
    sim : Bu_JpsiK_ee_eq_DPC
    dat : DATA*
  selection:
    psi_vt: B_const_mass_M > 5180
    mass  : (1)
    q2    : (1)
syst:
    - nom
fitting:
  ranges : # Fitting ranges for each brem category
    0 :
      - 2200
      - 3300
    1 :
      - 2200
      - 3800
    2 :
      - 2200
      - 3800
  mass    : Jpsi_M_brem_track_2 # Observable to be fitted
  weights : weight
  binning :
    nbins : 60
  model:
    pdfs:
      - dscb 
  simulation:
    strategy :
      retry  :
        ntries        : 4
        pvalue_thresh : 0.05
        ignore_status : true
