[project]
name            = "zfit-stubs"
description     = "Project with stub files for zfit"
readme          = "README.md"
version         = '0.0.1'
requires-python = ">=3.12"
dependencies    = []

[project.optional-dependencies]
dev = ["pytest"]
