args:
  - {sample : DATA_24*, trigger : Hlt2RD_BuToKpEE_MVA     , q2bin : jpsi }
  - {sample : DATA_24*, trigger : Hlt2RD_BuToKpMuMu_MVA   , q2bin : jpsi }
  - {sample : DATA_24*, trigger : Hlt2RD_B0ToKpPimEE_MVA  , q2bin : jpsi }
  - {sample : DATA_24*, trigger : Hlt2RD_B0ToKpPimMuMu_MVA, q2bin : jpsi }
output:
  - mass_cor_q2_def_jpsi.png
  - mass_org_q2_def_jpsi.png
