# This config file is used to configure the behaviour of RDFGetter12

definitions:
  MC: {}
  EE:
    q2      : Jpsi_M * Jpsi_M
    mva_cmb : BDT_cmb
    mva_prc : BDT_prc
  MM:
    q2      : Jpsi_M * Jpsi_M
    mva_cmb : BDT_cmb
    mva_prc : BDT_prc
