ntoys : 0
# ----------------
qsq_bin:
  - low
  - central
  - high
mva_cmb:
  - 0.30
  - 0.40
  - 0.50
  - 0.60
  - 0.70
  - 0.80
  - 0.85
  - 0.90
  - 0.92
  - 0.94
  - 0.95
mva_prc:
  - 0.30
  - 0.40
  - 0.50
  - 0.60
  - 0.70
  - 0.80
  - 0.85
  - 0.90
  - 0.92
  - 0.94
  - 0.95
