ntoys : 1
# ----------------
mva_cmb:
  - 0.30
  - 0.40
  - 0.50
  - 0.60
  - 0.70
  - 0.80
  - 0.85
  - 0.90
  - 0.92
  - 0.94
  - 0.95
  - 0.96
  - 0.97
  - 0.98
mva_prc:
  - 0.30
  - 0.40
  - 0.50
  - 0.60
  - 0.70
  - 0.80
  - 0.85
  - 0.90
  - 0.92
  - 0.94
  - 0.95
  - 0.96
  - 0.97
  - 0.98
