ntoys : 0
# ----------------
qsq_bin:
  - low
  - central
  - high
mva_cmb:
  - 300
  - 400
  - 500
  - 600
  - 700
  - 800
  - 850
  - 900
  - 920
  - 940
  - 950
mva_prc:
  - 300
  - 400
  - 500
  - 600
  - 700
  - 800
  - 850
  - 900
  - 920
  - 940
  - 950
