args:
  - {sample : Bd_Kstee_eq_btosllball05_DPC, trigger : Hlt2RD_B0ToKpPimEE_MVA, q2bin : low    }
  - {sample : Bd_Kstee_eq_btosllball05_DPC, trigger : Hlt2RD_B0ToKpPimEE_MVA, q2bin : central}
  - {sample : Bd_Kstee_eq_btosllball05_DPC, trigger : Hlt2RD_B0ToKpPimEE_MVA, q2bin : high   }
  # ------------
  - {sample : Bu_Kee_eq_btosllball05_DPC  , trigger : Hlt2RD_BuToKpEE_MVA   , q2bin : low    }
  - {sample : Bu_Kee_eq_btosllball05_DPC  , trigger : Hlt2RD_BuToKpEE_MVA   , q2bin : central}
  - {sample : Bu_Kee_eq_btosllball05_DPC  , trigger : Hlt2RD_BuToKpEE_MVA   , q2bin : high   }
  # ------------
  - {sample : Bd_JpsiKst_ee_eq_DPC        , trigger : Hlt2RD_B0ToKpPimEE_MVA, q2bin : jpsi   }
  - {sample : Bu_JpsiK_ee_eq_DPC          , trigger : Hlt2RD_BuToKpEE_MVA   , q2bin : jpsi   }
  # ------------
  - {sample : 'DATA_24*'                  , trigger : Hlt2RD_B0ToKpPimEE_MVA, q2bin : jpsi   }
  - {sample : 'DATA_24*'                  , trigger : Hlt2RD_BuToKpEE_MVA   , q2bin : jpsi   }
output:
  cleanup:
    - 1Trk_mas.png
    - 2Trk_mas.png
    - bmass_brem_corr.png
    - bmass_hop.png
    - bmass.png
    - mass_cascade.png
    - mass_jpsi_misid.png
    - mva_cmb.png
    - q2.png
