args:
  - {sample : Bu_JpsiK_ee_eq_DPC  , trigger : Hlt2RD_BuToKpEE_MVA     , q2bin : jpsi   }
  - {sample : Bu_JpsiK_mm_eq_DPC  , trigger : Hlt2RD_BuToKpMuMu_MVA   , q2bin : jpsi   }
  - {sample : Bd_JpsiKst_ee_eq_DPC, trigger : Hlt2RD_B0ToKpPimEE_MVA  , q2bin : jpsi   }
  - {sample : Bd_JpsiKst_mm_eq_DPC, trigger : Hlt2RD_B0ToKpPimMuMu_MVA, q2bin : jpsi   }
output:
  - bmass.png
  - jmass.png
