# This config file controls how the friend trees 
# of the first stage get made

stage_1:
  - {kind : hop           , project : rk_nopid, version : v1, parts : 10}
  - {kind : mass          , project : rk_nopid, version : v1, parts : 10}
  - {kind : brem_track_2  , project : rk_nopid, version : v1, parts : 10}
  - {kind : swp_cascade   , project : rk_nopid, version : v1, parts : 10}
  - {kind : swp_jpsi_misid, project : rk_nopid, version : v1, parts : 10}
stage_2:
  - {kind : mva           , project : rk_nopid, version : v8, parts : 30}
  - {kind : smear         , project : rk_nopid, version : v1, parts : 20}
