name: Publish Python ğŸ distribution ğŸ“¦ to PyPI and TestPyPI
on: push
jobs:
  build:
    name   : Build distribution
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-name: myenv
        create-args: >-
          python=3.12
          gxx
          root
        channels: conda-forge
        init-shell: bash
    - name: Define output directory 
      run: |
        ANADIR=$PWD/output
        echo  "ANADIR=$PWD/output" >> "$GITHUB_ENV"
    
        mkdir -p $ANADIR
    #-----------
    - name: Install project 
      run: |
        micromamba run -n myenv pip install .[fit,ml,dev]
    #-----------
    - name: Test
      run: |
        micromamba run -n myenv pytest tests
    #-----------
    - name: Install pypa/build
      run: >-
        micromamba run -n myenv  python3 -m
        pip install
        build
        --user
    #-----------
    - name: Build a binary wheel and a source tarball
      run:  micromamba run -n myenv python3 -m build
    #-----------
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
  #--------------------
  publish-to-pypi:
    name: >-
      Publish Python ğŸ distribution ğŸ“¦ to PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/data-manipulation-utilities
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution ğŸ“¦ to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
