# This is a config meant to specify how to emulate a sample

# ----------------------------------------
all:
  patching:
    3 : 5
    4 : 5
# ----------------------------------------
Bs_JpsiKst_mm_eq_DPC : 
  sample : Bd_JpsiKst_mm_eq_DPC
  redefine : &red_001
    B_M                  : B_M                  + 87.23
    B_Mass               : B_Mass               + 87.23
    B_M_brem_track_2     : B_M_brem_track_2     + 87.23
    B_const_mass_M       : B_const_mass_M       + 87.23
    B_const_mass_psi2S_M : B_const_mass_psi2S_M + 87.23
    B_ID                 : '531'
    B_TRUEID             : 'B_TRUEID          == 511 ? 531 :          B_TRUEID'
    Kst_MC_MOTHER_ID     : 'Kst_MC_MOTHER_ID  == 511 ? 531 :  Kst_MC_MOTHER_ID'
    Jpsi_MC_MOTHER_ID    : 'Jpsi_MC_MOTHER_ID == 511 ? 531 : Jpsi_MC_MOTHER_ID'
Bs_JpsiKst_ee_eq_DPC :
  sample : Bd_JpsiKst_ee_eq_DPC
  redefine :
    <<: *red_001
# ----------------------------------------
# These samples are meant to represent
# hadronic swapped (K -> pi and pi -> K) decays
# ----------------------------------------
Bd_JpsiKst_mm_had_swp:
  sample   : Bd_JpsiKst_mm_eq_DPC
Bd_JpsiKst_ee_had_swp:
  sample   : Bd_JpsiKst_ee_eq_DPC
# ----------------------------------------
Bs_JpsiX_mm_eq_JpsiInAcc:
  sample : Bs_JpsiX_mm_eq_JpsiInAcc
  patching:
    1 : 5
    2 : 5
    3 : 5
    4 : 5
# ----------------------------------------
Bu_JpsiX_mm_eq_JpsiInAcc:
  sample : Bu_JpsiX_mm_eq_JpsiInAcc
  patching:
    1 : 5
    2 : 5
    3 : 5
    4 : 5
# ----------------------------------------
Bd_psi2SKst_mm_eq_DPC:
  sample : Bd_psi2SKst_mm_eq_DPC
  patching:
    4 : 2
    3 : 2
    7 : 6
    8 : 6
# ----------------------------------------
Bd_psi2SKst_ee_eq_DPC:
  sample : Bd_psi2SKst_ee_eq_DPC
  patching:
    4 : 2
    3 : 2
